package se.mistral.backend.auth;

import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import se.mistral.backend.auth.dto.RegisterRequest;
import se.mistral.backend.exception.NotFoundException;
import se.mistral.backend.auth.dto.AuthResponse;
import se.mistral.backend.auth.dto.LoginRequest;
import se.mistral.backend.user.Role;
import se.mistral.backend.user.User;
import se.mistral.backend.user.UserRepository;

@Service
@RequiredArgsConstructor
public class AuthService {

    // these fields are filled in by the constructor generated by lombok
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;
    private final AuthenticationManager authenticationManager;

    public String register(RegisterRequest request) {
        if (userRepository.existsByEmail(request.email())) {
            throw new IllegalArgumentException("Email already in use: " + request.email());
        }
        /* TODO: don't default to making new users teachers (maybe add a Role field to the RegisterRequest or similar). */
        User user = User.builder()
            .name(request.name())
            .email(request.email())
            .password(passwordEncoder.encode(request.password()))
            .role(Role.TEACHER)
            .build();
        userRepository.save(user);
        
        return "Registration successful, your account is pending activation by an admin";
    }

    public AuthResponse login(LoginRequest request) {
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.email(), request.password()));
        User user = userRepository.findByEmail(request.email())
            .orElseThrow(() -> new NotFoundException("User not found"));
        return new AuthResponse(jwtService.generateToken(user), user.getEmail(), user.getName(), user.getRole().name());
    }
}
