spring.application.name=backend

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/mistral
spring.datasource.username=admin
spring.datasource.password=secret

# flyway
spring.flyway.enabled=true

# jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# jwt
jwt.secret=qMd4zRloaVkwy8vlY+/1+f/nixO9LrBvasNf15r4nAPwd7bgaqZWud4l93QQC0QKqwPgNyKcaYJRFU1RrfReXw==
jwt.expiration-ms=86400000
