spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mistral
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=qMd4zRloaVkwy8vlY+/1+f/nixO9LrBvasNf15r4nAPwd7bgaqZWud4l93QQC0QKqwPgNyKcaYJRFU1RrfReXw==
jwt.expiration-ms=86400000
