name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (node_modules/|target/|dist/|.*\.spec\.ts)
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_JAVA: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_ANGULAR: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true

